coverage:
  precision: 2
  round: down
  range: "70...100"
  notify:
    require_ci_to_pass: yes

  status:
    project: yes

    patch: yes

    changes: no
    
codecov:
  token: 3e72ecfa-b3cd-45cd-bc72-1f64b802c7b8
  
comment:
  layout: "header, diff, changes"
  behavior: default
  require_changes:no

